config/routes.rb
Rails.application.routes.draw do
  get 'photos/new'

  get 'comments/new'

  devise_for :users
  get 'welcome/index'

   root 'welcome#index'
  resources :comments
  
  resources :photos

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  
  validates :description, length: { minimum: 2, maximum: 140 }
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :user            #user_id -> User
  belongs_to :following_user, class_name: 'User'  #following_user_id -> User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected
  
  def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :avatar) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :authenticate_user!

  def new
    @comment = current_user.comments.build
  end

  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      redirect_to root_path
    else
      render :new
    end
  end

protected

  def comment_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    following = current_user.followings.build(following_user: @user)
    @success = following.save
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      if current_user 
        @comments = Comment.order("created_at desc")
         
      end
 
  end
 end
 
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/new.html.erb
<h1>Nuevo Comentario</h1>

<%= form_for @comment do |f| %>

  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="action">
    <%= f.submit "Aceptar" %>
  </div>

<% end %>

app/views/followings/create.html.erb
$("#following").html("<%= escape_javascript(render('users/following')) %>");
$("#following").css('background', 'red');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Bienvenidos al Mini-Twitter</h1>
<p class="notice" style="color: green"><%= notice %></p>
<p class="alert" style="color: red"><%= alert %></p>
 
 <% if user_signed_in? %>
     <%= link_to('Nuevo Comentario', new_comment_path) %>

<% else %>
    <p>Registrate</p>
<% end %>
  <%= yield %>

 <% if user_signed_in? %>
  
  <%= link_to('Edit registration', edit_user_registration_path) %><br>
  
<% else %>
  
  <%= link_to('Registro', new_user_registration_path)  %><br>
  
   
<% end %>
    
    
    <% if user_signed_in? %>
  
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>     <br>   
  
<% else %>
  
  <%= link_to('Login', new_user_session_path)  %>  <br>
  
<% end %>  
  
</body>
</html>

app/views/users/_followings.html.erb
<% if current_user %>
  <% if current_user.following?(@user) %>
    Ya sigues a <%= @user.email %>
  <% else %>
    <%= button_to "Seguir", followings_path(user_id: @user.id), remote: true %>
  <% end %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Comentarios de <%= @user.email %></h1>

<div id="following">
  <%= render 'following' %>
</div>

<%= render @comments %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <div class="comments">
      <% for comment in @comments %>
     
      

      <hr>
   
        <div class="comments">
          <%= comment.description %>
         <br><span>by: <%= comment.user.email %>
           <li class="round-image-50"> <%= image_tag(current_user.avatar.url(:thumb)) %></li>
          <br><%= time_ago_in_words("comment.created_at_date") %>
          
</span>
          <hr>
        </div>

      <% end %>
    </div>

    
<% end %>




      